apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbonpilot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carbonpilot
  template:
    metadata:
      labels:
        app: carbonpilot
    spec:
      containers:
        - name: carbonpilot
          image: carbonpilot:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: carbonpilot-service
spec:
  selector:
    app: carbonpilot
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
